---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-admin
rules:
  - apigroups: [""]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin
  namespace: devops-tools
 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: jenkins-admin
roleRef:
 apiGroup: rbac.authorization.8s.io
 kind: ClusterRole
 name: jenkins-admin
subjects:
-kind: ServiceAccount
 name: jenkins-admin
 namespace: devops-tools
 
 

