---

- name: Borrar pods anteriores
  shell: kubeadm reset -f

- name: borrar .kube
  shell: rm -r -f /root/.kube

- name: Crear red 
  shell: kubeadm init --pod-network-cidr 192.169.0.0/16

- name: export kubeconfig
  shell: export KUBECONFIG=/etc/kubernetes/admin.conf
 
- name: Crear carpeta .kube
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: u=rw,g=r,o=r
    recurse: yes

- name: copiar fichero admin.conf
  shell: cp -i /etc/kubernetes/admin.conf /root/.kube/config

- name: cambia permisos 
  shell: chown $(id -u):$(id -g) /root/.kube/config

- name: almacenar en una variable el join
  command: kubeadm token create --print-join-command
  register: token_join

- name: guardar join en fichero
  local_action: copy content="{{ token_join.stdout }}" dest=files/join_nodes.sh

